#!/bin/sh
# @author: Matthew Story <matthewstory@gmail.com>
#          William Baxter <web@superscript.com>
# A 54lines compliance checker
shout() { echo "$0: $*" >&2; }
barf() { shout "$*"; exit 100; }
safe() { "$@" || barf "cannot $*"; }
usage() { echo "usage: $0 <file|->" >&2; exit 100; }

# validate
[ $# -lt 1 ] && usage
if [ "$1" = '-' ]
then
    shift
else
    [ -f "$1" ] || barf "$check is not a file"
fi
exec awk '{
    lines += 1
    if (54 < lines) exit 54
    gsub(/\t/,"        ",$0)
    if (80 < length($0)) exit 80
}' "$@"
